# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Distance Calculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Distance Calculator
  pod 'DistanceGetter' , '~> 0.1'

  target 'Distance CalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Distance CalculatorUITests' do
    # Pods for testing
  end

end
