# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Currency Conversion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Currency Conversion
  pod 'CurrencyRequest', '~> 0.1'

  target 'Currency ConversionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Currency ConversionUITests' do
    # Pods for testing
  end

end
